Add Tales from the Ashlands - The Great Hive Baan Binif
loot/morrowind pull request #112
Opened 2024-12-31 02:24 UTC by poperigby

https://www.nexusmods.com/morrowind/mods/51419

2024-12-31 11:55 UTC, MacSplody requested changes
Just a few minor format changes required.

2024-12-31 11:55 UTC, MacSplody commented on masterlist.yaml
> +      - 'Bal''laku - The Lonely Towers.esp'
Closing forward slash on links.
Lists with a single entry can be formatted as a single line with square brackets.
And a newline can be should be used to separate files from different mods.

```suggestion
  - name: 'Baan_Binif.ESP'
    url: 'https://www.nexusmods.com/morrowind/mods/51419/'
    after: [ 'Bal''laku - The Lonely Towers.esp' ]

```

2025-01-01 05:45 UTC, poperigby commented
Thanks for the tips :)

2025-01-03 21:20 UTC, merged

2025-01-03 21:20 UTC, pStyl3 commented
Thanks!