Add merged objects patch
loot/morrowind pull request #46
Opened 2021-10-21 20:35 UTC by IllusiveMan196

2021-10-22 01:01 UTC, MacSplody requested changes
Two changes required, and one other suggestion.

2021-10-22 01:01 UTC, MacSplody commented on masterlist.yaml
> +  - name: 'Merged Objects.esp'
You could add the location for the mod.

```suggestion
  - name: 'Merged Objects.esp'
    url: [ 'https://www.nexusmods.com/morrowind/mods/46870/' ]
```

2021-10-22 01:01 UTC, MacSplody commented on masterlist.yaml
> +            url: [https://www.nexusmods.com/morrowind/mods/46870]
For links in messages use `[example](https://www.example.com/)`.
Add a newline between separate mods as well.

```suggestion
            text: 'Regenerate after adding or removing mods changing or adding in-game items. Use [TES3Merge](https://www.nexusmods.com/morrowind/mods/46870/)'

```

> Regenerate after adding or removing mods changing or adding in-game items.

Wording could be changed slightly.

> Regenerate after adding or removing mods that change or add in-game items.

2021-10-22 15:31 UTC, IllusiveMan196 commented
Added proposed changes, also more logical order of patches.

2021-10-23 01:55 UTC, MacSplody requested changes

2021-10-23 01:55 UTC, MacSplody commented on masterlist.yaml
> +  # Latest LOOT Thread
Not related to adding merged objects, so it should be done in a separate pull request,
```suggestion
# Latest LOOT Thread
```

2021-10-23 01:55 UTC, MacSplody commented on masterlist.yaml
> +  # Official DLC
```suggestion
# Official DLC
```

2021-10-23 01:55 UTC, MacSplody commented on masterlist.yaml
> +  # Official Mods
```suggestion
# Official Mods
```

2021-10-23 01:55 UTC, MacSplody commented on masterlist.yaml
> +  # Unofficial Patches
```suggestion
# Unofficial Patches
```

2021-10-23 01:55 UTC, MacSplody commented on masterlist.yaml
> +  #Other Mods (default)
```suggestion
#Other Mods (default)
```

2021-10-23 01:55 UTC, MacSplody commented on masterlist.yaml
> +  #Any dynamic patches
Kind of related, but we should match section name and formatting from the other masterlists.

```suggestion
###### Modding Tools - Generated Files ######
```

2021-10-23 01:55 UTC, MacSplody commented on masterlist.yaml
> +      - 'Merged Objects.esp'
Single entry lists can be placed in brackets.
```suggestion
    after: [ 'Merged Objects.esp' ]
```

2021-10-23 01:55 UTC, MacSplody commented on masterlist.yaml
> +            text: 'Regenerate after adding or removing mods or generating [Merged Objects.esp](https://www.nexusmods.com/morrowind/mods/46870/)'
Missing newline at the end of file.

![image](https://user-images.githubusercontent.com/1944639/138538111-3c5b5802-e408-4941-b8c4-a756e36c2f24.png)

```suggestion
            text: 'Regenerate after adding or removing mods or generating [Merged Objects.esp](https://www.nexusmods.com/morrowind/mods/46870/)'

```

2021-10-24 01:53 UTC, MacSplody commented on masterlist.yaml
> +  # Other Fixes
```suggestion
# Other Fixes
```

2021-10-24 01:54 UTC, MacSplody approved these changes

2021-10-24 02:08 UTC, merged

2021-10-24 02:08 UTC, MacSplody commented
@IllusiveMan196 Thanks.