Add Beautiful Cities of Morrowind main files
loot/morrowind pull request #51
Opened 2021-10-25 23:24 UTC by IllusiveMan196

Add location
Add load order
First step in "closing" this [issue](https://github.com/IllusiveMan196/morrowind/issues/2)
#52

2021-10-26 17:23 UTC, MacSplody commented
> First step in "closing" this [issue](https://github.com/IllusiveMan196/morrowind/issues/2)

Files from the same mod page can be added in one pull request.
And all files from that modpage should be kept with the main file, unless they're replacement plugins for other mods.

2021-10-26 20:57 UTC, IllusiveMan196 commented
Well, this makes it way easier at least now. A moment, I've got those files added in local version already. Forgot alpahbetical oder of files... another edit?

2021-10-26 21:06 UTC, MacSplody commented on masterlist.yaml
> +      - name: 'BOM_OpenMW_plazas.esp'
We'll only add spaces if the files are from different mods.

```suggestion
  - name: 'Beautiful cities of Morrowind.ESP'
    url: [ 'https://www.nexusmods.com/morrowind/mods/49231/' ]
    after:
      - 'Better Landscapes Stonewood Pass (RP Edit).esp'
      - 'Morrowind Anti-Cheese.esp'
  - name: 'BOM_pathgrid_reset.esp'
    url: [ 'https://www.nexusmods.com/morrowind/mods/49231/' ]
    after:
      - name: 'Beautiful cities of Morrowind.ESP'
      - name: 'multipatch.esp'
  - name: 'BOM_OpenMW_plazas.esp'
    url: [ 'https://www.nexusmods.com/morrowind/mods/49231/' ]
    after:
      - name: 'Beautiful cities of Morrowind.ESP'
      - name: 'multipatch.esp'
      - name: 'BOM_pathgrid_reset.esp'
  - name: 'Interior exterior flag reset.esp'
    url: [ 'https://www.nexusmods.com/morrowind/mods/49231/' ]
    after:
      - name: 'Beautiful cities of Morrowind.ESP'
      - name: 'multipatch.esp'
      - name: 'BOM_pathgrid_reset.esp'
      - name: 'BOM_OpenMW_plazas.esp'
```

2021-10-28 04:34 UTC, MacSplody commented
@IllusiveMan196 Are you happy with that? It can be merged if it's done.
Though you could make one or two format changes.

2021-10-28 04:43 UTC, MacSplody commented on masterlist.yaml
> +      - name: 'multipatch.esp'
```suggestion
    after:
      - 'Beautiful cities of Morrowind.ESP'
      - 'multipatch.esp'
```

2021-10-28 04:44 UTC, MacSplody commented on masterlist.yaml
> +      - name: 'BOM_pathgrid_reset.esp'
```suggestion
      - 'Beautiful cities of Morrowind.ESP'
      - 'BOM_pathgrid_reset.esp'
      - 'multipatch.esp'
```

2021-10-28 04:45 UTC, MacSplody commented on masterlist.yaml
> +      - name: 'BOM_OpenMW_plazas.esp'
```suggestion
      - 'Beautiful cities of Morrowind.ESP'
      - 'BOM_OpenMW_plazas.esp'
      - 'BOM_pathgrid_reset.esp'
      - 'multipatch.esp'
```

2021-10-28 04:45 UTC, MacSplody requested changes
Just a few format changes required.

2021-10-28 08:36 UTC, MacSplody approved these changes

2021-10-28 09:19 UTC, merged

2021-10-28 09:20 UTC, MacSplody commented
@IllusiveMan196 Thanks.