Miscellaneous Fixes to masterlist
loot/morrowind pull request #80
Opened 2022-03-24 00:49 UTC by IllusiveMan196

BCoM load rule enhancements
Vanilla Quest Overhaul load rule
MasterIndexRedux added with load rule

2022-03-24 00:54 UTC, sibir-ine commented
This should be split into at least two PRs, one for the BCoM rules & one for the Vanilla Quest Tweaks rule.

2022-03-24 00:59 UTC, IllusiveMan196 commented
For one line?

2022-03-24 01:53 UTC, sibir-ine commented
Yes, PRs should stay focused on a single theme whether it be, e.g., updates for a single mod or Bash Tags or cleaning data for several mods.

2022-03-25 03:01 UTC, sibir-ine requested changes

2022-03-25 03:01 UTC, sibir-ine commented on masterlist.yaml
> +    after: [ 'Religions Elaborated.ESP' ]
This can be removed from this PR now:

```suggestion
```

2022-03-25 03:04 UTC, sibir-ine commented on masterlist.yaml
> +      - 'Unofficial Morrowind Official Plugins Patched.ESP'
This is already handled by groups:

```suggestion
```

2022-03-25 03:13 UTC, sibir-ine commented on masterlist.yaml
> +
LOOT should sort this way by default:

```suggestion
```

2022-03-26 00:41 UTC, sibir-ine approved these changes

2022-03-26 00:44 UTC, merged